#!/usr/bin/env bash
# Server-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to identify IdentifyFile
SSH-add ~/.ssh/school

# Username and IP Address
ssh ubuntu@34.227.89.142
